WITH CLM AS (
    SELECT 
        CLAIM_ID, 
		SUBMISSION_DATE,
        GROSS, 
        PATIENTSHARE, 
        NET, 
        VAT 
    FROM CLAIM_MASTER
),
DIAG AS (
    SELECT 
        CLAIM_ID, 
        COUNT(DIAGNOSIS_CODE) TOTAL_DIAGNOSIS 
    FROM CLAIM_DIAGNOSIS 
    GROUP BY CLAIM_ID
),
ACT AS (
    SELECT 
        CLAIM_ID, 
        COUNT(ACTIVITY_ID) TOT_ACTIVITIES, 
        SUM(ACT_NET_PRICE * ACT_QUANTITY) GROSS 
    FROM CLAIM_ACTIVITY 
    GROUP BY CLAIM_ID
),
FINAL AS (
    SELECT 
		CLM.CLAIM_ID,
		CLM.SUBMISSION_DATE,
		CLM.GROSS,
		CLM.PATIENTSHARE,
		CLM.NET,
		CLM.VAT,
		DIAG.TOTAL_DIAGNOSIS,
		ACT.TOT_ACTIVITIES,
        ACT.GROSS ACTUAL_GROSS
    FROM CLM 
    LEFT JOIN(DIAG) USING (CLAIM_ID)
	LEFT JOIN(ACT) USING (CLAIM_ID)
)
SELECT * FROM FINAL